version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "433:433"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    networks:
      - inception

networks:
  inception:
    driver: bridge