version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    env_file: .env
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    
  mariadb:
    image: mariadb
    container_name: mariadb
    env_file: .env
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress
    container_name: wordpress
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES}/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES}/mariadb
      o: bind

networks:
  inception:
    driver: bridge